Update for relase of v2.0.0 - Candidate I
UncomplicatedCustomServer/UncomplicatedCustomRoles pull request #15
Opened 2024-05-22 18:18 UTC by FoxWorn3365

2024-05-22 21:33 UTC, SpGerg requested changes
e

2024-05-22 21:33 UTC, SpGerg commented on UncomplicatedCustomRoles/Extensions/PlayerExtension.cs
> +            if (HasCustomRole(player))
Make out argument?

2024-05-22 21:33 UTC, SpGerg commented on UncomplicatedCustomRoles/Extensions/PlayerExtension.cs
> +        }
It will be throw exception

2024-05-22 21:33 UTC, SpGerg commented on UncomplicatedCustomRoles/Extensions/Vector3Extension.cs
> +        }
What....

2024-05-22 21:33 UTC, SpGerg commented on UncomplicatedCustomRoles/Interfaces/ICustomRole.cs
> +        public abstract bool IgnoreSpawnSystem { get; set; }
You need decomposite this things.

2024-05-22 21:33 UTC, SpGerg commented on UncomplicatedCustomRoles/Interfaces/IUCRCommand.cs
> +        public bool Executor(List<string> arguments, ICommandSender sender, out string response);
Execute?

2024-05-22 21:33 UTC, SpGerg commented on UncomplicatedCustomRoles/Interfaces/IUCRCommand.cs
> +        public bool Executor(List<string> arguments, ICommandSender sender, out string response);
Also watch command system in Paganism console, it is pretty cool.

2024-05-22 21:33 UTC, SpGerg commented on UncomplicatedCustomRoles/Plugin.cs
> +        internal static Plugin Instance;
For some plugins Instance maybe useful

2024-05-24 21:38 UTC, DrAgenda approved these changes
Imagine

2024-05-24 21:40 UTC, SpGerg commented
Goodnt

2024-05-24 21:42 UTC, merged

2024-05-24 21:48 UTC, SpGerg requested changes

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/API/Features/CustomRole.cs
> +        public static Dictionary<int, int> Alive { get; } = Plugin.PlayerRegistry;
=>

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/API/Features/CustomRole.cs
> +            return Plugin.RolesCount[Role.Id].Count;
It will be throw exception, add contains check

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/API/Features/CustomRole.cs
> +            if (Plugin.CustomRoles.ContainsKey(id))
`Plugin.CustomRoles.TryGetValue(id, out var result)`

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Commands/CommandParent.cs
> +        public List<IUCRCommand> RegisteredCommands { get; } = new();
Must be upper

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Commands/UCRSpawn.cs
> +                int Id = int.Parse(arguments[1]);
id

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Commands/UCRSpawn.cs
> +                if (!Plugin.CustomRoles.ContainsKey(Id))
TryGetValue

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Extensions/Vector3Extension.cs
> +    public static class Vector3Extension
All this class is idiotly

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Interfaces/ICustomRole.cs
> +    }
Decomposite this shit.

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Manager/FileConfigs.cs
> +        public bool Is(string localDir = "")
localDirectory

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Manager/FileConfigs.cs
>          internal string Dir = Path.Combine(Paths.Configs, "UncomplicatedCustomRoles");
Directory

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Manager/FileConfigs.cs
> +        public void LoadAll(string localDir = "")
localDirectory

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Manager/FileConfigs.cs
> +            foreach (string FileName in List(localDir))
fileName

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Manager/FileConfigs.cs
> +        public void Welcome(string localDir = "")
localDirectory

2024-05-24 21:48 UTC, SpGerg commented on UncomplicatedCustomRoles/Manager/SpawnManager.cs
> +                if (Action[0].ToUpper() == "IR")
Make enum for this